// ============================================================
// Sehat Saathi - MCP Tool: send_email_alert
// (Model Context Protocol - Tool Definition)
// ============================================================
// KAGGLE REQUIREMENT: MCP Server / Tool
//
// PURPOSE: This is the "MCP Tool" that Agent 3 can call autonomously.
// In the Model Context Protocol paradigm, tools are well-defined
// functions with schemas that LLM agents can invoke to take
// real-world actions.
//
// This tool uses:
//   - PRIMARY:  Resend API (https://resend.com) — modern email API
//   - FALLBACK: Nodemailer SMTP — universal email fallback
//
// TOOL CONTRACT (Schema that Agent 3 understands):
//   Tool Name: send_email_alert
//   Parameters:
//     - patientEmail: string  (destination email)
//     - subject: string       (email subject line)
//     - message: string       (email body, may be HTML)
//     - alertType: string     ('CRITICAL' | 'WARNING' | 'REMINDER')
//   Returns:
//     - { success: boolean, messageId: string, provider: string }
//
// WHY THIS IS "MCP":
//   Agent 3 receives this tool's schema and decides WHEN to call it.
//   The agent doesn't blindly send emails — it reasons about whether
//   the pharmacist's findings justify an alert, then invokes this tool.
// ============================================================

import { Resend } from "resend";
import nodemailer from "nodemailer";

// Initialize Resend client
const resend = new Resend(process.env.RESEND_API_KEY);

// Initialize Nodemailer SMTP transport (fallback)
const smtpTransport = nodemailer.createTransport({
  host: process.env.SMTP_HOST || "smtp.gmail.com",
  port: parseInt(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Generate HTML email template based on alert type
 * @param {string} alertType - 'CRITICAL' | 'WARNING' | 'REMINDER'
 * @param {string} message   - Email body content
 * @returns {string}         - HTML email string
 */
function generateEmailHTML(alertType, message) {
  const colors = {
    CRITICAL: { bg: "#FEF2F2", border: "#DC2626", icon: "🚨", badge: "#DC2626" },
    WARNING: { bg: "#FFFBEB", border: "#D97706", icon: "⚠️", badge: "#D97706" },
    REMINDER: { bg: "#EFF6FF", border: "#2563EB", icon: "💊", badge: "#2563EB" },
  };

  const style = colors[alertType] || colors.REMINDER;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Sehat Saathi Alert</title>
</head>
<body style="font-family: 'Helvetica Neue', Arial, sans-serif; background: #F9FAFB; margin: 0; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
    
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #0F172A, #1E3A5F); padding: 24px; text-align: center;">
      <h1 style="color: white; margin: 0; font-size: 24px;">
        🏥 Sehat Saathi
      </h1>
      <p style="color: #94A3B8; margin: 4px 0 0 0; font-size: 14px;">
        Intelligent Medication Management
      </p>
    </div>
    
    <!-- Alert Badge -->
    <div style="background: ${style.bg}; border-left: 4px solid ${style.border}; padding: 16px 24px; margin: 0;">
      <div style="display: flex; align-items: center; gap: 8px;">
        <span style="font-size: 24px;">${style.icon}</span>
        <span style="background: ${style.badge}; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 700; letter-spacing: 0.5px;">
          ${alertType} ALERT
        </span>
      </div>
    </div>
    
    <!-- Content -->
    <div style="padding: 24px;">
      <div style="color: #374151; line-height: 1.7; font-size: 15px;">
        ${message.replace(/\n/g, "<br>")}
      </div>
    </div>
    
    <!-- Footer -->
    <div style="background: #F8FAFC; padding: 16px 24px; border-top: 1px solid #E2E8F0; text-align: center;">
      <p style="color: #94A3B8; font-size: 12px; margin: 0;">
        This alert was automatically generated by Sehat Saathi's multi-agent system.
        <br>
        <strong>⚕️ Always consult your healthcare provider for medical decisions.</strong>
      </p>
      <p style="color: #CBD5E1; font-size: 11px; margin: 8px 0 0 0;">
        PII has been masked in this alert for your privacy. | Sehat Saathi © 2025
      </p>
    </div>
  </div>
</body>
</html>`;
}

/**
 * MCP TOOL: send_email_alert
 * ============================================================
 * THE CORE MCP TOOL — Agent 3 calls this autonomously
 *
 * This function represents a "Model Context Protocol Tool" —
 * a well-defined, schema-validated action that an LLM agent
 * can invoke to cause a real-world side effect (sending an email).
 *
 * Agent 3 decides WHETHER to call this tool based on its reasoning.
 * If Agent 2 reports a CRITICAL drug interaction, Agent 3 will
 * autonomously invoke this tool without human intervention.
 *
 * @param {string} patientEmail - Recipient email address
 * @param {string} subject      - Email subject
 * @param {string} message      - Email body (plain text or HTML)
 * @param {string} alertType    - 'CRITICAL' | 'WARNING' | 'REMINDER'
 * @returns {Promise<Object>}   - Send result with provider info
 */
export async function sendEmailAlert(
  patientEmail,
  subject,
  message,
  alertType = "WARNING"
) {
  console.log(
    `📧 [MCP Tool: send_email_alert] Initiating ${alertType} email to: ${patientEmail}`
  );

  const htmlContent = generateEmailHTML(alertType, message);

  // ============================================================
  // ATTEMPT 1: Resend API (Primary Provider)
  // Resend is a modern email API with excellent deliverability
  // and developer experience. Preferred for hackathon demos.
  // ============================================================
  if (process.env.RESEND_API_KEY && process.env.RESEND_API_KEY !== "your_resend_api_key_here") {
    try {
      console.log("📧 [MCP Tool] Trying Resend API...");
      console.log('Routing email to verified developer address due to Sandbox limits.');
      const actualToEmail = process.env.VERIFIED_EMAIL || patientEmail;

      const { data, error } = await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL || "alerts@sehatsaathi.com",
        to: [actualToEmail],
        subject: subject,
        html: htmlContent,
        text: message, // Fallback plain text
      });

      if (error) {
        throw new Error(`Resend error: ${error.message}`);
      }

      console.log(`✅ [MCP Tool] Email sent via Resend. ID: ${data.id}`);
      return {
        success: true,
        messageId: data.id,
        provider: "Resend",
        alertType,
        timestamp: new Date().toISOString(),
      };
    } catch (resendError) {
      console.warn(
        `⚠️ [MCP Tool] Resend failed: ${resendError.message}. Trying SMTP fallback...`
      );
    }
  }

  // ============================================================
  // ATTEMPT 2: Nodemailer SMTP (Fallback Provider)
  // Universal fallback using standard SMTP protocol.
  // Works with Gmail, SendGrid, Mailgun, and any SMTP server.
  // ============================================================
  if (process.env.SMTP_USER && process.env.SMTP_USER !== "your_email@gmail.com") {
    try {
      console.log("📧 [MCP Tool] Trying Nodemailer SMTP fallback...");

      const mailOptions = {
        from: `"Sehat Saathi" <${process.env.SMTP_USER}>`,
        to: patientEmail,
        subject: subject,
        text: message,
        html: htmlContent,
      };

      const info = await smtpTransport.sendMail(mailOptions);

      console.log(`✅ [MCP Tool] Email sent via SMTP. ID: ${info.messageId}`);
      return {
        success: true,
        messageId: info.messageId,
        provider: "Nodemailer-SMTP",
        alertType,
        timestamp: new Date().toISOString(),
      };
    } catch (smtpError) {
      console.error(`❌ [MCP Tool] SMTP fallback also failed: ${smtpError.message}`);
      throw new Error(`All email providers failed. Last error: ${smtpError.message}`);
    }
  }

  // ============================================================
  // DEMO MODE: Simulate email sending when no keys are configured
  // ============================================================
  console.log(
    "📧 [MCP Tool: DEMO MODE] Simulating email send (no real keys configured)"
  );
  return {
    success: true,
    messageId: `demo-${Date.now()}`,
    provider: "Demo-Simulation",
    alertType,
    timestamp: new Date().toISOString(),
    note: "Email simulated — configure RESEND_API_KEY or SMTP credentials to send real emails",
  };
}

/**
 * MCP TOOL SCHEMA — The "contract" that Agent 3 uses to understand
 * when and how to invoke this tool.
 *
 * This schema follows the OpenAI Function Calling / MCP Tool format.
 * Agent 3 receives this schema and uses it for decision-making.
 */
export const sendEmailAlertSchema = {
  name: "send_email_alert",
  description:
    "Sends an emergency or reminder email alert to the patient. Use this tool when: (1) A CRITICAL or MODERATE drug interaction is detected that poses immediate health risk, (2) A medication reminder needs to be set. Do NOT call this for LOW severity interactions.",
  parameters: {
    type: "object",
    properties: {
      patientEmail: {
        type: "string",
        description: "The patient's email address for receiving the alert",
      },
      subject: {
        type: "string",
        description:
          "Clear, urgent email subject line describing the alert type",
      },
      message: {
        type: "string",
        description:
          "Detailed email body with specific interaction information and patient-friendly recommendations",
      },
      alertType: {
        type: "string",
        enum: ["CRITICAL", "WARNING", "REMINDER"],
        description:
          "CRITICAL for life-threatening interactions, WARNING for moderate, REMINDER for scheduled medication reminders",
      },
    },
    required: ["patientEmail", "subject", "message", "alertType"],
  },
};
